

export const LOGIN_USER ="LOGIN_USER"
export const LOGOUT_USER ="LOGOUT_USER"
export const LOAD_USER ="LOAD_USER"
export const FAIL_USER ="FAIL_USER"
export const CURRENT_USER ="CURRENT_USER"
export const REGISTER_USER ="REGISTER_USER"



export const GET_USERS_LOAD = "GET_USERS_LOAD";
export const GET_USERS_SUCCESS = "GET_USERS_SUCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const LOAD_VERIFICATION_REGISTER_USER ='LOAD_VERIFICATION_REGISTER_USER'
export const VERIFICATION_REGISTER_USER = "VERIFICATION_REGISTER_USER"
export const FAIL_VERIFICATION_REGISTER_USER = "FAIL_VERIFICATION_REGISTER_USER"


export const  LOAD_CONFIRMATION_TOKEN="LOAD_CONFIRMATION_TOKEN"
export const  CONFIRMATION_TOKEN_SUCCES ="CONFIRMATION_TOKEN_SUCCES"
export const  CONFIRMATION_TOKEN_FAIL = "CONFIRMATION_TOKEN_FAIL"

export const  SAVE_USER = 'SAVE_USER'


export const  LOAD_ADVANCE_USER ="LOAD_ADVANCE_USER"
export const  ADD_ADVANCED_USER_SUCCES ="ADD_ADVANCED_USER_SUCCES"
export const  ADD_ADVANCED_USER_FAIL= "ADD_ADVANCED_USER_FAIL"

export const   LOAD_DELETE_USER = "LOAD_DELETE_USER"
export const   DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const   DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const   LOAD_DELETE_TOKEN = "LOAD_DELETE_TOKEN"
export const   DELETE_TOKEN_SUCCESS = 'DELETE_TOKEN_SUCCESS'
export const   DELETE_TOKEN_FAIL = "DELETE_TOKEN_FAIL"

export const  GET_ADV_USR_LOAD = "GET_ADV_USR_LOAD "
export const  GET_ADV_USR_SUCCESS = 'GET_ADV_USR_SUCCESS'
export const  GET_ADV_USR_FAIL = "GET_ADV_USR_FAIL"

export const  GET_USRS_JOB_LOAD = "GET_USRS_JOB_LOAD"
export const  GET_USRS_JOB_SUCCESS = 'GET_USRS_JOB_SUCCESS'
export const  GET_USRS_JOB_FAIL = 'GET_USRS_JOB_FAIL '

export const  GET_USRS_JOB_REGION_LOAD = "GET_USRS_JOB_REGION_LOAD"
export const  GET_USRS_JOB_REGION_SUCCESS = "GET_USRS_JOB_REGION_SUCCESS"
export const  GET_USRS_JOB_REGION_FAIL = "GET_USRS_JOB_REGION_FAIL"

export const   LOAD_DELETE_ADV_USER = "LOAD_DELETE_ADV_USER"
export const   DELETE_ADV_USER_SUCCESS = 'ELETE_ADV_USER_SUCCESS'
export const   DELETE_ADV_USER_FAIL = 'DELETE_ADV_USER_FAIL'

export const CLEAR_SERVICE_REDUCER_LOUGOUT ="CLEAR_SERVICE_REDUCER_LOUGOUT"